### ISSUE TITLE
Is the leaderboard still maintain ?

### ISSUE THREAD

**Issue by vTuanpham** [ZaloAI-Jaist/VMLU#4]
I have email [contact@vmlu.ai](mailto:contact@vmlu.ai) two time with no responses over the past two weeks.

Would like to actually verify my model results and be shown on the leaderboard. :confused:

**Comment by ZaloAI-Jaist** [comment]
@vTuanpham yes we still maintain the leaderboard, yet the frequency is less than previously. Please be patient and keep developing new models :)

**Comment by vTuanpham** [comment]
Our model has been added :D, thank you for your support
